config/routes.rb
MobileSample::Application.routes.draw do

  root :to => "notes#index"

  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to_mobile_requests :skip_xhr_requests => false

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    if @note.save
      redirect_to @note, notice: 'Note was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    if @note.update_attributes(params[:note])
      redirect_to @note, notice: 'Note was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to notes_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Normal Version!</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21868921-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile Version!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application" %>

  <%= javascript_include_tag "application.mobile.js" %>
  <%= stylesheet_link_tag    "application.mobile.css" %>

  <%= csrf_meta_tags %>
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21868921-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
</head>
<body>
<div data-role="page">
  <%= yield %>
  <div data-role="footer" data-position="fixed">
    <div data-role="navbar">
      <ul>
        <li>
          <%= link_to notes_path, :class => ("ui-btn-active" if action_name == 'index'), :"data-icon" => "home", :"data-iconpos" => "top" do %>
            Home
          <% end %>
        </li>
        <li>
          <%= link_to new_note_path, :class => ("ui-btn-active" if action_name == 'new'), :"data-icon" => "plus", :"data-iconpos" => "top" do %>
            New Note
          <% end %>
          </li>
        </ul>
    </div>
  </div>
</div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_form.mobile.erb
<div data-role="content">
  <%= form_for(@note) do |f| %>
    <% if @note.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/edit.mobile.erb
<div data-role="header">
  <h1>Editing note</h1>
  <%= link_to "Cancel", note_path(@note), :"data-icon" => "delete", :class => "ui-btn-right" %>
</div>

<%= render 'form' %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.title %></td>
    <td><%= note.body %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/index.mobile.erb
<div data-role="header">
  <h1>Notes</h1>
</div>

<div data-role="content">
  <ul data-role="listview">
  <% @notes.each do |note| %>
    <li>
    <%= link_to note do %>
      <h2><%= note.title %></h2>
      <%= truncate(note.body, :length => 25) %>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/new.mobile.erb
<div data-role="header">
  <h1>New note</h1>
  <%= link_to "Cancel", notes_path, :"data-icon" => "delete", :class => "ui-btn-right" %>
</div>

<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Body:</b>
  <%= @note.body %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/notes/show.mobile.erb
<div data-role="header">
  <%= link_to "Back", notes_path, :"data-icon" => "arrow-l", :class => "ui-btn-left" %>
  <h1><%= @note.title %></h1>
  <%= link_to "Edit", edit_note_path(@note), :"data-icon" => "gear", :class => "ui-btn-right" %>

  <div data-role="navbar">
    <ul>
      <li>
        <%= link_to @note, :confirm => 'Are you sure?', :method => :delete, :"data-icon" => "delete", :"data-iconpos" => "top" do %>
          Delete
        <% end %>
      </li>
    </ul>
  </div>
</div>


<div data-role="content">
  <p id="notice"><%= notice %></p>
  <p>
    <%= @note.body %>
  </p>
</div>